apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: enterprise-rag
data:
  # 환경 설정
  ENVIRONMENT: "production"
  AWS_REGION: "us-east-1"
  
  # Kafka 설정
  KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "AWS_MSK_IAM"
  
  # Redis 설정
  REDIS_ENDPOINT: "${REDIS_ENDPOINT}"
  REDIS_PORT: "6379"
  REDIS_SSL: "true"
  
  # OpenSearch 설정
  OPENSEARCH_ENDPOINT: "${OPENSEARCH_ENDPOINT}"
  OPENSEARCH_PORT: "443"
  OPENSEARCH_USE_SSL: "true"
  OPENSEARCH_INDEX: "enterprise-rag"
  
  # S3 설정
  S3_BUCKET: "${S3_BUCKET}"
  
  # Bedrock 설정
  BEDROCK_REGION: "us-east-1"
  EMBEDDING_MODEL: "amazon.titan-embed-text-v1"
  
  # 로그 레벨
  LOG_LEVEL: "INFO"
  
  # 성능 설정
  BATCH_SIZE: "100"
  MAX_WORKERS: "10"
  TIMEOUT_SECONDS: "30"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config-dev
  namespace: enterprise-rag-dev
data:
  # 개발 환경 설정
  ENVIRONMENT: "development"
  AWS_REGION: "us-east-1"
  
  # Kafka 설정
  KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "AWS_MSK_IAM"
  
  # Redis 설정
  REDIS_ENDPOINT: "${REDIS_ENDPOINT}"
  REDIS_PORT: "6379"
  REDIS_SSL: "true"
  
  # OpenSearch 설정
  OPENSEARCH_ENDPOINT: "${OPENSEARCH_ENDPOINT}"
  OPENSEARCH_PORT: "443"
  OPENSEARCH_USE_SSL: "true"
  OPENSEARCH_INDEX: "enterprise-rag-dev"
  
  # S3 설정
  S3_BUCKET: "${S3_BUCKET}"
  
  # Bedrock 설정
  BEDROCK_REGION: "us-east-1"
  EMBEDDING_MODEL: "amazon.titan-embed-text-v1"
  
  # 로그 레벨
  LOG_LEVEL: "DEBUG"
  
  # 성능 설정
  BATCH_SIZE: "50"
  MAX_WORKERS: "5"
  TIMEOUT_SECONDS: "60"