apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-extraction-service
  namespace: enterprise-rag
  labels:
    app: text-extraction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-extraction-service
  template:
    metadata:
      labels:
        app: text-extraction-service
    spec:
      containers:
      - name: text-extraction
        image: enterprise-rag-platform/text-extraction:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AWS_REGION
        - name: SERVICE_NAME
          value: "text-extraction-service"
        - name: SERVICE_VERSION
          value: "1.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: text-extraction-service
  namespace: enterprise-rag
spec:
  selector:
    app: text-extraction-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
