apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api-service
  namespace: enterprise-rag
  labels:
    app: search-api-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-api-service
  template:
    metadata:
      labels:
        app: search-api-service
    spec:
      containers:
      - name: search-api
        image: enterprise-rag-platform/search-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: OPENSEARCH_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: OPENSEARCH_ENDPOINT
        - name: OPENSEARCH_INDEX
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: OPENSEARCH_INDEX
        - name: REDIS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: REDIS_ENDPOINT
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AWS_REGION
        - name: EMBEDDING_MODEL
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: EMBEDDING_MODEL
        - name: SERVICE_NAME
          value: "search-api-service"
        - name: SERVICE_VERSION
          value: "1.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: search-api-service
  namespace: enterprise-rag
spec:
  selector:
    app: search-api-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP