# Jaeger values for distributed tracing
allInOne:
  enabled: true
  image:
    tag: "1.50"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

storage:
  type: memory
  memory:
    max-traces: 50000

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

ingress:
  enabled: false

